SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO AS RI
INNER JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS MAX_RI
ON RI.FOOD_TYPE = MAX_RI.FOOD_TYPE AND MAX_RI.FAVORITES = RI.FAVORITES
ORDER BY FOOD_TYPE DESC;