SELECT 
    YEAR, MONTH, GENDER, COUNT(*) AS USERS
FROM 
    USER_INFO AS A
INNER JOIN (
    SELECT 
        USER_ID, 
        YEAR(SALES_DATE) AS YEAR, 
        MONTH(SALES_DATE) AS MONTH
    FROM 
        ONLINE_SALE
    GROUP BY -- 해당 달에 두번 구매했어도 하나로 카운트 되어야 함.
        USER_ID, YEAR(SALES_DATE), MONTH(SALES_DATE) 
) AS B
ON 
    A.USER_ID = B.USER_ID
WHERE 
    GENDER IS NOT NULL
GROUP BY 
    YEAR, MONTH, GENDER
ORDER BY 
    YEAR, MONTH, GENDER;
