SELECT 
    A.ID,
    A.GENOTYPE,
    B.PARENT_GENOTYPE
FROM
    ECOLI_DATA AS A
INNER JOIN (
        SELECT 
            ID, GENOTYPE AS PARENT_GENOTYPE
        FROM 
            ECOLI_DATA
    ) AS B
ON
    A.PARENT_ID = B.ID
WHERE
    GENOTYPE & PARENT_GENOTYPE = PARENT_GENOTYPE
ORDER BY
    A.ID ASC;