-- 테이블 구조 파악
# SELECT *
# FROM FISH_INFO;

SELECT 
    COUNT(*) AS FISH_COUNT
FROM
    FISH_INFO FI
INNER JOIN 
    FISH_NAME_INFO FNI
ON 
    FI.FISH_TYPE = FNI.FISH_TYPE
WHERE 
    FNI.FISH_NAME IN ('BASS', 'SNAPPER');