-- ORACLE의 경우에는 YEAR, MONTH 함수가 존재하지 않는다.
-- TO_CHAR이나 EXTRACT를 통해 진행해야 한다. (추후 정리)
-- 추가적으로 ORACLE은 AS를 붙이지 않는다.

SELECT 
    A.TITLE, A.BOARD_ID,
    B.REPLY_ID, B.WRITER_ID, B.CONTENTS, TO_CHAR(B.CREATED_DATE,'YYYY-MM-DD')
FROM 
    USED_GOODS_BOARD A
INNER JOIN
    USED_GOODS_REPLY B
ON 
    A.BOARD_ID = B.BOARD_ID
WHERE
    TO_CHAR(A.CREATED_DATE,'YYYY') = '2022'
AND
    TO_CHAR(A.CREATED_DATE, 'MM') = '10'
ORDER BY
    B.CREATED_DATE ASC, A.TITLE ASC;