SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
INNER JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
    GROUP BY CATEGORY
) AS MAX_FP
ON FP.CATEGORY = MAX_FP.CATEGORY AND MAX_FP.MAX_PRICE = FP.PRICE
ORDER BY MAX_PRICE DESC;