SELECT
    PRICE_GROUP,
    COUNT(*) AS PRODUCTS
FROM 
    PRODUCT
INNER JOIN (
    SELECT
        PRODUCT_ID,
        FLOOR(PRICE / 10000) * 10000 AS PRICE_GROUP
    FROM 
        PRODUCT
) AS GROUP_SUBQUERY
USING
    (PRODUCT_ID)
GROUP BY
    PRICE_GROUP
ORDER BY
    PRICE_GROUP ASC;
    
